<?php

namespace Proxies\__CG__\Login\LoginBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Country extends \Login\LoginBundle\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setContinent($continent)
    {
        $this->__load();
        return parent::setContinent($continent);
    }

    public function getContinent()
    {
        $this->__load();
        return parent::getContinent();
    }

    public function setRegion($region)
    {
        $this->__load();
        return parent::setRegion($region);
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }

    public function setSurfacearea($surfacearea)
    {
        $this->__load();
        return parent::setSurfacearea($surfacearea);
    }

    public function getSurfacearea()
    {
        $this->__load();
        return parent::getSurfacearea();
    }

    public function setIndepyear($indepyear)
    {
        $this->__load();
        return parent::setIndepyear($indepyear);
    }

    public function getIndepyear()
    {
        $this->__load();
        return parent::getIndepyear();
    }

    public function setPopulation($population)
    {
        $this->__load();
        return parent::setPopulation($population);
    }

    public function getPopulation()
    {
        $this->__load();
        return parent::getPopulation();
    }

    public function setLifeexpectancy($lifeexpectancy)
    {
        $this->__load();
        return parent::setLifeexpectancy($lifeexpectancy);
    }

    public function getLifeexpectancy()
    {
        $this->__load();
        return parent::getLifeexpectancy();
    }

    public function setGnp($gnp)
    {
        $this->__load();
        return parent::setGnp($gnp);
    }

    public function getGnp()
    {
        $this->__load();
        return parent::getGnp();
    }

    public function setGnpold($gnpold)
    {
        $this->__load();
        return parent::setGnpold($gnpold);
    }

    public function getGnpold()
    {
        $this->__load();
        return parent::getGnpold();
    }

    public function setLocalname($localname)
    {
        $this->__load();
        return parent::setLocalname($localname);
    }

    public function getLocalname()
    {
        $this->__load();
        return parent::getLocalname();
    }

    public function setGovernmentform($governmentform)
    {
        $this->__load();
        return parent::setGovernmentform($governmentform);
    }

    public function getGovernmentform()
    {
        $this->__load();
        return parent::getGovernmentform();
    }

    public function setHeadofstate($headofstate)
    {
        $this->__load();
        return parent::setHeadofstate($headofstate);
    }

    public function getHeadofstate()
    {
        $this->__load();
        return parent::getHeadofstate();
    }

    public function setCapital($capital)
    {
        $this->__load();
        return parent::setCapital($capital);
    }

    public function getCapital()
    {
        $this->__load();
        return parent::getCapital();
    }

    public function setCode2($code2)
    {
        $this->__load();
        return parent::setCode2($code2);
    }

    public function getCode2()
    {
        $this->__load();
        return parent::getCode2();
    }

    public function getCode()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["code"];
        }
        $this->__load();
        return parent::getCode();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'continent', 'region', 'surfacearea', 'indepyear', 'population', 'lifeexpectancy', 'gnp', 'gnpold', 'localname', 'governmentform', 'headofstate', 'capital', 'code2', 'code');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}